# Generated by Django 4.1 on 2022-08-22 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='level',
            old_name='learning_game_objective_weights',
            new_name='objective_weights',
        ),
        migrations.AddField(
            model_name='learningobjective',
            name='example',
            field=models.CharField(max_length=360, null=True),
        ),
        migrations.AlterField(
            model_name='learningobjective',
            name='description',
            field=models.CharField(max_length=360),
        ),
    ]
