# Generated by Django 4.1 on 2022-11-17 13:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0002_rename_learning_game_objective_weights_level_objective_weights_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ObjectiveRequirements',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=240)),
                ('target', models.FloatField(blank=True)),
                ('tolerance', models.FloatField(blank=True)),
                ('json', models.JSONField()),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.gameobjective')),
            ],
        ),
        migrations.CreateModel(
            name='ObjectiveResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('totalTime', models.FloatField()),
                ('complete', models.BooleanField()),
                ('actual', models.FloatField(blank=True)),
                ('json', models.JSONField()),
                ('requirements', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.objectiverequirements')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='InWorldItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transform', models.JSONField()),
                ('needs_collection', models.BooleanField()),
                ('is_interactable', models.BooleanField()),
                ('is_ghost', models.BooleanField()),
                ('is_visible', models.BooleanField()),
                ('is_trigger', models.BooleanField()),
                ('keep_apart_group', models.IntegerField(blank=True)),
                ('keep_close_group', models.IntegerField(blank=True)),
                ('paint_needed', models.IntegerField(blank=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.item')),
            ],
        ),
        migrations.AddField(
            model_name='level',
            name='objective_requirement',
            field=models.ManyToManyField(blank=True, to='api.objectiverequirements'),
        ),
    ]
