# Generated by Django 4.1 on 2022-11-17 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_objectiverequirements_objectiveresponse_inworlditem_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='objectiverequirements',
            name='json',
            field=models.JSONField(blank=True),
        ),
    ]
