# Generated by Django 4.1 on 2022-11-17 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_objectiverequirements_json'),
    ]

    operations = [
        migrations.AlterField(
            model_name='objectiverequirements',
            name='json',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='objectiverequirements',
            name='target',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='objectiverequirements',
            name='tolerance',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
