# Generated by Django 4.1 on 2022-11-17 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_objectiverequirements_json_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='objectiverequirements',
            name='json',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
