# Generated by Django 4.1 on 2022-11-17 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_objectiverequirements_json'),
    ]

    operations = [
        migrations.AlterField(
            model_name='level',
            name='tools',
            field=models.ManyToManyField(blank=b'I01\n', to='api.tool'),
        ),
    ]
