# Generated by Django 4.1 on 2022-11-17 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_level_tools'),
    ]

    operations = [
        migrations.RenameField(
            model_name='level',
            old_name='objective_requirement',
            new_name='objective_requirements',
        ),
    ]
