# Generated by Django 4.1 on 2022-12-28 17:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('api', '__first__'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InitialMainBayesianNetwork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('graph', models.JSONField(blank=True, default=dict, null=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('date_published', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='LearningObjectiveTrajectory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('graph', models.JSONField(blank=True, default=dict, null=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('date_published', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserMainBayesianNetwork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('network', models.JSONField(blank=True, default=dict, null=True)),
                ('score', models.CharField(default='M', max_length=1)),
                ('user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserGameObjectiveBayesianNetwork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('network', models.JSONField(blank=True, default=dict, null=True)),
                ('score', models.CharField(default='M', max_length=1)),
                ('gameObjective', models.ManyToManyField(to='api.gameobjective')),
                ('user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserGameData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('closed_learning_objectives', models.ManyToManyField(related_name='closed_learning_objectives', to='api.learningobjective')),
                ('completed_levels', models.ManyToManyField(related_name='completed_levels', to='api.level')),
                ('recommended_levels', models.ManyToManyField(related_name='recommended_levels', to='api.level')),
                ('unlocked_learning_objectives', models.ManyToManyField(related_name='unlocked_learning_objectives', to='api.learningobjective')),
                ('unlocked_levels', models.ManyToManyField(related_name='unlocked_levels', to='api.level')),
                ('user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='InitialGameObjectiveBayesianNetwork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('graph', models.JSONField(blank=True, default=dict, null=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('date_published', models.DateTimeField(auto_now_add=True)),
                ('game_objective', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='api.gameobjective')),
            ],
        ),
    ]
